### ISSUE TITLE
Titles are always overwritten from Telldus Live

### ISSUE THREAD

**Issue by cederstrom** [xibriz/ImportTelldusLive#1]
The title of a device or sensor is always overwritten from Telldus Live when synchronizing. If I change the title of a device in Z-Way it will be overwritten with the name from Telldus with the next sync.
I would like to change this to be an optional behavior. Perhaps a boolean config called "Always use name from Telldus Live".

If it is ok with you @xibriz I would gladly create a pull request with a proposal :)

**Comment by xibriz** [comment]
Please do that. Contributions are always welcome!

**Comment by cederstrom** [comment]
There we go :)
