### ISSUE TITLE
Ignored devices and sensors are being fetched

### ISSUE THREAD

**Issue by cederstrom** [xibriz/ImportTelldusLive#3]
I live in a neighborhood where we, obviously, have a lot of home automaters :) I get signals from about 20+ sensors which I have ignored in Telldus Live.

@xibriz: Is it by design that this plugin calls Telldus Live with request parameter `includeIgnored=1`?
If this is not by design I would like to submit a pull request changing the behavior to `includeIgnored=0`

**Comment by xibriz** [comment]
It was just something I used for testing purposes. To get the maximum number of devices to test with.

Just submit a pull request on that. I will update the app in Z-Way tomorrow.

**Comment by cederstrom** [comment]
Done! Thanks :)
