### ISSUE TITLE
Wrong if condition

### ISSUE THREAD

**Issue by PoltoS** [xibriz/ImportTelldusLive#6]
Comma (`,`) should be replaced by `&&` https://github.com/xibriz/ImportTelldusLive/blob/ea7fa3a79c3ffc2f5edfd5da61a85767d56da92e/index.js#L142

**Comment by xibriz** [comment]
I have fixed the issue, but it's valid syntax ref:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comma_Operator

**Comment by PoltoS** [comment]
It is not valid here as with comma the evaluation will continue even if the first is false. With && it will abort on false and skip the statement inside if. This is what you wanted

**Comment by PoltoS** [comment]
Tha ks for fixing. Will you upload it to developer.z-wave.me?

**Comment by xibriz** [comment]
@PoltoS I forgot how to do it... do you have any idea of where the documentation is on publishing new versions?

**Comment by PoltoS** [comment]
Log in to developer.z-wave.me, find your module, upload a new version of the archive.

You can also go to userModules folder and use the `./uploadModule.sh <moduleName> <login> <password>` script
